root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/highlight-bundle
        permanent: false

docs:
    pattern: /docs
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /docs/highlight-bundle
        permanent: false

highlight:
    resource: "@HighlightBundle/Resources/config/routing.yml"
    prefix:   /docs/highlight-bundle
